name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# added .net 10 to runner env
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: dotnet build BackendApiWasmDemo.sln

  test:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Test
        run: dotnet test BackendApiWasmDemo.sln

  push-image:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    needs: [build, test]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Build and push image
        run: |
          docker build -f ./GameApi/Dockerfile -t ${{ secrets.docker_username}}/tankgame:${{ github.sha }} .
          docker push ${{ secrets.docker_username }}/tankgame:${{ github.sha }}

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    needs: [push-image]
    env:
      GITHUB_SHA: ${{ github.sha }}
      NAMESPACE: tankgame
    steps:
      - uses: actions/checkout@v5
      - name: Deploy on k8s
        run: |
          cat deployment/api.yml | envsubst | kubectl apply -f -