name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Building
        run: |
          which docker git
          docker build -f ./GameApi/dockerfile -t ${{ secrets.docker_username}}/tankgame:${{ github.sha }} .
          docker push ${{ secrets.docker_username }}/tankgame:${{ github.sha }}


  deploy:
    runs-on: self-hosted
    needs: [build]
    env:
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v5
      - name: Deploy on k8s
        run: |
          cat deployment/api.yml | envsubst | kubectl apply -f -

            # make it run again!!!